rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
branches:
  only:
    - master
notifications:
  email:
    - tim@github.com
env:
  - PUPPET_VERSION=2.6.14
  - PUPPET_VERSION=2.7.12
matrix:
  exclude:
    - rvm: 1.9.2
      env: PUPPET_VERSION=2.6.14
    - rvm: 1.9.3
      env: PUPPET_VERSION=2.6.14
