language: ruby
cache: bundler
bundler_args: --without development

rvm:
  - 2.1
  - 1.9.3
  - 2.0.0

sudo: false

env:
  - PUPPET_GEM_VERSION='~> 4.3.0' COVERAGE=yes
  - PUPPET_GEM_VERSION='~> 2.7.0'
  - PUPPET_GEM_VERSION='~> 3.7.0'
  - PUPPET_GEM_VERSION='~> 3.8.0'
  - PUPPET_GEM_VERSION='~> 4.0.0'
  - PUPPET_GEM_VERSION='~> 4.1.0'
  - PUPPET_GEM_VERSION='~> 4.2.0'
  - PUPPET_GEM_VERSION='~> 4.3.0'
  - PUPPET_GEM_VERSION='https://github.com/puppetlabs/puppet.git#master'
  - PUPPET_GEM_VERSION='https://github.com/puppetlabs/puppet.git#stable'
  - PUPPET_GEM_VERSION='https://github.com/puppetlabs/puppet.git#3.x'

matrix:
  include:
    # these versions are explicitly needed for ruby 1.8.7 support
    - rvm: 1.8.7
      env: PUPPET_GEM_VERSION='~> 3.8.0' RSPEC_GEM_VERSION='= 3.1.0'
    - rvm: 1.8.7
      env: PUPPET_GEM_VERSION='~> 2.7.0' RSPEC_GEM_VERSION='~> 2.14.0'

  exclude:
    # newer puppet versions don't run on 1.8.7
    - rvm: 1.8.7
      env: PUPPET_GEM_VERSION='~> 4.0.0'
    - rvm: 1.8.7
      env: PUPPET_GEM_VERSION='~> 4.1.0'
    - rvm: 2.1
      env: PUPPET_GEM_VERSION='~> 4.1.0'
    # puppet 2.7 doesn't run on newer rubies
    - rvm: 1.9.3
      env: PUPPET_GEM_VERSION='~> 2.7.0'
    - rvm: 2.0.0
      env: PUPPET_GEM_VERSION='~> 2.7.0'
    - rvm: 2.1
      env: PUPPET_GEM_VERSION='~> 2.7.0'
    # run Coveralls exactly once
    - rvm: 1.9.3
      env: PUPPET_GEM_VERSION='~> 4.3.0' COVERAGE=yes
    - rvm: 2.0.0
      env: PUPPET_GEM_VERSION='~> 4.3.0' COVERAGE=yes

  allow_failures:
    - env: PUPPET_GEM_VERSION='git:https://github.com/puppetlabs/puppet.git#master'
    - rvm: 1.8.7

notifications:
  email:
    - tim@github.com
