encoding: UTF-8
kramdown:
    input: GFM
    hard_wrap: false
    math_engine: mathjax
future: true
gfm_quirks: paragraph_end
lsi: false
safe: true
incremental: false
gist:
    noscript: false
markdown: kramdown
